### PR TITLE
Using Imperative annotate command

### PR DESCRIPTION
**Pull request by tshaiman**
- showing an alternative and faster way to annotate a pod using the annotate command

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for providing the change. Any reason why you closed the PR again?

**Comment by tshaiman** [comment]
It was a mess for some reason and contained unnecessary commits
Will re create soon

**Comment by tshaiman** [comment]
Recreated it now.

p.s : ingress is not part of the curriculum , right ?

**Comment by bmuschko** [comment]
> p.s : ingress is not part of the curriculum , right ?

Correct.

**Pull request closed without merging**
